### ISSUE TITLE
Można zbyt wiele razy dodać tę samą akcję do ulubionych

### ISSUE THREAD

**Issue by pwohlfahrt** [news-s/Trading-Dashboard#12]
W endpointcie add_fav trzeba dodać ifa do sprawdzania czy użytkownik ma tę akcję w ulubionych. Jeśli tak, zwrócić error

**Comment by jjyutm4532** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the add_fav function to check if the user already has the stock in their favorites before adding it. If the stock is already in favorites, an error message is returned.

You can review changes in this commit: https://github.com/jjyutm4532/news-s-Trading-Dashboard-12/commit/7c3670e40f6c9acb823414681d8d917c427868c1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
